# Generated by Django 6.0.1 on 2026-02-06 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0002_district_province_alter_indicator_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicator',
            name='data',
        ),
    ]
