# Generated by Django 6.0.1 on 2026-06-02 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0003_remove_indicator_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicatorvalue',
            name='year',
            field=models.IntegerField(default=2022),
        ),
    ]
