# Generated by Django 6.0.1 on 2026-06-02 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0004_indicatorvalue_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='year',
            field=models.IntegerField(default=2022),
        ),
    ]
