# Generated by Django 6.0.1 on 2026-06-07 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0005_indicator_year'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[('UPLOAD', 'Dataset Upload'), ('COMPUTE', 'Indicator Computation'), ('USER_CREATE', 'User Created'), ('USER_UPDATE', 'User Updated'), ('USER_DELETE', 'User Deleted'), ('LOGIN', 'Admin Login'), ('LOGOUT', 'Admin Logout'), ('DATA_DELETE', 'Data Deleted'), ('OTHER', 'Other')], default='OTHER', max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('details', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('success', models.BooleanField(default=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DHSUploadedDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recode_type', models.CharField(choices=[('HR', 'Household Recode (HR)'), ('PR', 'Household Members Recode (PR)'), ('IR', 'Individual (Women) Recode (IR)'), ('MR', 'Men Recode (MR)'), ('KR', 'Children Recode (KR)'), ('BR', 'Births Recode (BR)'), ('CR', 'Couples Recode (CR)')], max_length=10)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('year', models.IntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('num_rows', models.IntegerField(blank=True, null=True)),
                ('num_vars', models.IntegerField(blank=True, null=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
                'unique_together': {('recode_type', 'year')},
            },
        ),
    ]
